apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pitstop-configmap  # Add this line to specify a name for the Kustomization
configMapGenerator:
  - files:
      - ../../.env
    name: pitstop-configmap
